@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class TLSVObservation{

             Observation.identifier => [None..None]
             Observation.status => [None..None]
             Observation.category => [None..None]
             Observation.code => [None..None]
             Observation.subject => [1..None]
             Observation.encounter => [None..None]
             Observation.effective[x] => [1..None]
             Observation.issued => [None..None]
             Observation.performer => [None..None]
             Observation.value[x] => [None..None]
             Observation.dataAbsentReason => [None..None]
             Observation.interpretation => [None..None]
             Observation.note => [None..None]
             Observation.bodySite => [None..None]
             Observation.method => [None..None]
             Observation.device => [None..None]
             Observation.referenceRange => [None..None]
             Observation.derivedFrom => [None..None]
             Observation.component => [None..None]
         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{

        class TLSVCategory  

     TLSVObservation -[#black,dotted,thickness=2]-> TLSVCategory
       }

package "Ressources de base" #palegreen {

 class "Observation" as  classc680d437163cc6bab4f9bdb35c3073d0 

    classc680d437163cc6bab4f9bdb35c3073d0 --> TLSVObservation
}
@enduml